version: 1.0.{build}
image: Visual Studio 2017
branches:
  only:
  - master
skip_non_tags: true

build_script:
  - dotnet build NetGrpcPrometheus.sln --configuration Release

test_script:
  - dotnet test NetGrpcPrometheusTest/NetGrpcPrometheusTest.csproj

after_test:
  - ps: |
      dotnet pack NetGrpcPrometheus/NetGrpcPrometheus.csproj -c Release /p:PackageVersion=$env:appveyor_repo_tag_name
      dotnet nuget push NetGrpcPrometheus/bin/Release/NetGrpcPrometheus.$env:appveyor_repo_tag_name.nupkg -k $env:API_KEY_SECRET -s https://www.nuget.org
