version: 1.0.{build}
image: Visual Studio 2017

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

environment:
  API_KEY_SECRET:
    secure: pHwfrpT3WI+xkvHkGHjzqg2WwmGz+Qx4oN3L/o4iPq+N84EdJOT74bq9j60NMrFs

skip_branch_with_pr: true
branches:
  only:
  - master

build_script:
  - dotnet build NetGrpcPrometheus.sln --configuration Release

test_script:
  - dotnet test NetGrpcPrometheusTest/NetGrpcPrometheusTest.csproj

deploy_script:
  - ps: |
      dotnet pack NetGrpcPrometheus/NetGrpcPrometheus.csproj -c Release
      dotnet nuget push NetGrpcPrometheus/bin/Release/NetGrpcPrometheus.*.nupkg -k $env:API_KEY_SECRET -s https://www.nuget.org
